### ISSUE TITLE
suggestion backlink to mastodon 

### ISSUE THREAD

**Issue by viisauksena** [circuscode/tootpress#18]
thx a lot for this easy to use tool,
i would suggest to make the mastodon icon, or the datestamp a backlink to the mastodon article itself _ similar to the tags

**Comment by circuscode** [comment]
Thank you. Your feature request I have already on my list. I will prioritize it for the next update. I will do it that way, to provide a setting activating the link to the original mastodon post. The link will be behind the mastodon icon. But not sure, when I will be able to deliver the update. Hopefully in Q1/Q2.

**Comment by circuscode** [comment]
As promised. Just released version 0.3 of the plugin, which includes the backlink feature. You can download it from here. But it will also be distributed via WordPress Plugin Directory in the next days.
