### ISSUE TITLE
next page link wont work on main page

### ISSUE THREAD

**Issue by viisauksena** [circuscode/tootpress#19]
i have an issue with the "next" page 
first it would be nice to also display only 5 toots .. 
then 
on https://strandcafe.fr/ the subpage /2 cant be found .. 
https://strandcafe.fr/2/
the toots should be there - but i cant find them - anything i can do?
it may be that this is my mainpage.

the original toots are from 
https://freiburg.social/@strandcafe

**Comment by viisauksena** [comment]
i quickly made a subpage socialmedia - the error is gone , but it is redirected all the time to the latest 10,
in the example before it also worked like that with /startseite/{1,2,3,4,5}
i can look also further into it in the - but not this week - thx so far

**Comment by circuscode** [comment]
Go to WordPress/Settings/Permalinks and just save the current settings again. This will refresh the WordPress-internal Permalink-Structure (including the TootPress-Permalinks). With a bit of luck, the error is solved and you can navigate through all your toots. Make sure, cleaning the cache, if you use a caching plugin. In general, this update of permalink settings, which is required in some cases, is a little bit annoying. It cannot be forced by the plugin in all cases.

**Comment by viisauksena** [comment]
magic _ i dont know what has changed by reclicking _ but it does the magic, at least for the tested subpage 
thx a lot

**Comment by circuscode** [comment]
Unfortunately, I must admit, that the root cause of the issue above was a wrong workflow in the code. /o\ This is now solved with Version 0.3 of the plugin. In the future there is no need to update the permalink structure manually in WordPress. Now it will be triggered automaticly, if required.
